name: sgmsas
region: fra
static_sites:
  - name: sgmsas-web
    github:
      repo: Didap/sgmsas
      branch: main
      deploy_on_push: true
    build_command: npm install -g pnpm && pnpm install && pnpm build
    output_dir: dist
    catchall_document: index.html
    environment_slug: node-js
domains:
  - domain: sgmsas.it
    type: PRIMARY
